on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-lint:
    name: Backend Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: pip install black flake8
        
      - name: Create .flake8 configuration file
        run: |
          echo "[flake8]" > .flake8
          echo "max-line-length = 200" >> .flake8
          echo "extend-ignore = E402" >> .flake8
          
      - name: Run Black
        run: black .
      
      - name: Run Flake8
        run: flake8 .

  backend-tests:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: pip install pytest
      
      - name: Add sample test
        run: |
          mkdir -p backend/tests
          echo "import unittest\nfrom backend.app import add\n\nclass TestApp(unittest.TestCase):\n    def test_add(self):\n        self.assertEqual(add(1, 2), 3)\n        self.assertEqual(add(-1, 1), 0)\n        self.assertEqual(add(0, 0), 0)\n\nif __name__ == '__main__':\n    unittest.main()" > backend/tests/test_app.py
      
      - name: Run tests
        run: pytest backend/tests

